### ISSUE TITLE
issue running prepare.py

### ISSUE THREAD

**Issue by aartivnkt** [karpathy/nanoGPT#107]
Hi, 
Thanks so much for nanoGPT. I have installed the dependencies and trying out the `prepare.py` code on python 3.10.4 virtual env. 

I see the following errors, seems related to installation of packages. I have installed all dependencies, using numpy == 1.24.1 and torch==1.31.1. I have also installed the other packages successfully: transformers, datasets, tiktoken, wandb and tqdm

```
(venv-3-10-4) aartiv@kg36-40-gpu1:~/nanoGPT/data/openwebtext$ python prepare.py
Traceback (most recent call last):
  File "/home/aartiv/nanoGPT/data/openwebtext/prepare.py", line 7, in <module>
    from datasets import load_dataset # huggingface datasets
  File "/home/aartiv/.pyenv/versions/venv-3-10-4/lib/python3.10/site-packages/datasets/__init__.py", line 43, in <module>
    from .arrow_dataset import Dataset
  File "/home/aartiv/.pyenv/versions/venv-3-10-4/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 56, in <module>
    import pandas as pd
  File "/home/aartiv/.pyenv/versions/venv-3-10-4/lib/python3.10/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
  File "/home/aartiv/.pyenv/versions/venv-3-10-4/lib/python3.10/site-packages/pandas/compat/__init__.py", line 18, in <module>
    from pandas.compat.numpy import (
  File "/home/aartiv/.pyenv/versions/venv-3-10-4/lib/python3.10/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/home/aartiv/.pyenv/versions/venv-3-10-4/lib/python3.10/site-packages/pandas/util/__init__.py", line 8, in <module>
    from pandas.core.util.hashing import (  # noqa:F401
  File "/home/aartiv/.pyenv/versions/venv-3-10-4/lib/python3.10/site-packages/pandas/core/util/hashing.py", line 24, in <module>
    from pandas.core.dtypes.common import (
  File "/home/aartiv/.pyenv/versions/venv-3-10-4/lib/python3.10/site-packages/pandas/core/dtypes/common.py", line 27, in <module>
    from pandas.core.dtypes.base import _registry as registry
  File "/home/aartiv/.pyenv/versions/venv-3-10-4/lib/python3.10/site-packages/pandas/core/dtypes/base.py", line 24, in <module>
    from pandas.errors import AbstractMethodError
  File "/home/aartiv/.pyenv/versions/venv-3-10-4/lib/python3.10/site-packages/pandas/errors/__init__.py", line 6, in <module>
    import ctypes
  File "/home/aartiv/.pyenv/versions/3.10.4/lib/python3.10/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'`
``
Any insight into how to fix this would be great! Thanks very much

**Comment by aartivnkt** [comment]
Update: I think the issue was with my python installation using pyenv. I tested prepare.py on a different python version and it works well. Thank you!
