### ISSUE TITLE
sample with --init_from=gpt2-xl error 

### ISSUE THREAD

**Issue by mchinen** [karpathy/nanoGPT#126]
I'm able to train and use the checkpoint for sampling sucessfully.
However, when using the downloaded pretrained weights with `--init_from=gpt2-xl` I get the following error:

```
python sample.py --init_from=gpt2-xl  --start="Large Language Models (LLMs) are becoming increasingly popular.  One of the uses for it is" --device=cpu --num_samples=5 --max_new_tokens=100
Overriding: init_from = gpt2-xl
Overriding: start = Large Language Models (LLMs) are becoming increasingly popular.  One of the uses for it is
Overriding: device = cpu
Overriding: num_samples = 5
Overriding: max_new_tokens = 100
loading weights from pretrained gpt: gpt2-xl
number of parameters: 1557.69M
Traceback (most recent call last):
  File "/home/mchinen/scm/nanoGPT/sample.py", line 49, in <module>
    model = GPT.from_pretrained(init_from, dict(dropout=0.0))
  File "/home/mchinen/scm/nanoGPT/model.py", line 255, in from_pretrained
    assert sd_hf[k].shape == sd[k].shape
AssertionError
```

**Comment by lantiga** [comment]
Can you update to the latest `main` and try again?

**Comment by mchinen** [comment]
Ah, `master` works, my repo was two days stale.
