### ISSUE TITLE
Encountered problems with the new dataset.

### ISSUE THREAD

**Issue by yinghaodang** [karpathy/nanoGPT#131]
When 
```
python train.py config/train_shakespeare_char.py
```
is OK.

but I changed the dataset, I get the problem:
```
Traceback (most recent call last):
  File "train.py", line 254, in <module>
    losses = estimate_loss()
  File "/home/yinghaodang/software/miniconda3/envs/GPT/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "train.py", line 215, in estimate_loss
    logits, loss = model(X, Y)
  File "/home/yinghaodang/software/miniconda3/envs/GPT/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yinghaodang/projects/nanoGPT/model.py", line 198, in forward
    loss = F.cross_entropy(logits.view(-1, logits.size(-1)), targets.view(-1), ignore_index=-1)
  File "/home/yinghaodang/software/miniconda3/envs/GPT/lib/python3.8/site-packages/torch/nn/functional.py", line 3026, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
```
I use pytorch1.13，and I make "compile = False"
I think the above problems may be caused by some dimension problems, but I don't know how to solve them.

this is config:
```
out_dir = 'out-longzu' #changed
eval_interval = 250 # keep frequent because we'll overfit
eval_iters = 200
log_interval = 10 # don't print too often

# we expect to overfit on this small dataset, so only save when val improves
always_save_checkpoint = False

wandb_log = False # override via command line if you like
wandb_project = 'shakespeare-char' # I don't know how to change.
wandb_run_name = 'mini-gpt'

dataset = 'longzu'  #changed
batch_size = 64
block_size = 256 # context of up to 256 previous characters

# baby GPT model :)
n_layer = 6
n_head = 6
n_embd = 384
dropout = 0.2

learning_rate = 1e-3 # with baby networks can afford to go a bit higher
max_iters = 5000
lr_decay_iters = 5000 # make equal to max_iters usually
min_lr = 1e-4 # learning_rate / 10 usually
beta2 = 0.99 # make a bit bigger because number of tokens per iter is small

warmup_iters = 100 # not super necessary potentially

compile = False
```
command is 
``` 
python train.py config/train_longzu.py
```
by the way, I use 'cpu' is OK, but that is too slow.
I run in WSL2, It has 8GB of video memory.

**Comment by yinghaodang** [comment]
I tried solve the problem.
![image](https://user-images.githubusercontent.com/49315320/217460269-f97e3d55-67fd-46ea-a2b5-2d32ad0693a8.png)
![image](https://user-images.githubusercontent.com/49315320/217460651-e91c984e-8ba3-4e58-aaa3-572c0f7598ad.png)
please help me...

**Comment by yinghaodang** [comment]
![image](https://user-images.githubusercontent.com/49315320/217465751-27427e24-03e3-4a3c-a6ef-0cfab75e10e9.png)

**Comment by venzen** [comment]
Your train.py script looks OK. 

What is the output of the prepare.py script with your new data?

To run train.py, do you use cpu or GPU? I ask because you have `dropout = 0.2` but cpu wants `dropout = 0.0` and the pytorch nightly build. You can get an installation command at [https://pytorch.org/get-started/locally/](https://pytorch.org/get-started/locally/)
