### ISSUE TITLE
how to train  on M1 ?

### ISSUE THREAD

**Issue by yangboz** [karpathy/nanoGPT#150]
I am trying to run  train.py on my MBP M1
but it throws error as following:
```
ctx = nullcontext() if device_type == 'cpu' else torch.amp.autocast(device_type=device_type, dtype=ptdtype)
AttributeError: module 'torch' has no attribute 'amp'
```
Any idea?
thanks,

**Comment by abcdggs** [comment]
I'm having the same issue, I think it is a torch versioning error. Will report back when I find a solution

**Comment by abcdggs** [comment]
To get it working, I created a new conda env using python=3.8
Installed Torch & Dependencies
```
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu118
pip3 install numpy transformers datasets tiktoken wandb tqdm
```
Above is Preview version of Pytorch.

Working correctly now

**Comment by yangboz** [comment]
> To get it working, I created a new conda env using python=3.8 Installed Torch & Dependencies
> 
> ```
> pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu118
> pip3 install numpy transformers datasets tiktoken wandb tqdm
> ```
> 
> Above is Preview version of Pytorch.
> 
> Working correctly now

let's have a try , thanks man.

**Comment by nexthybrid** [comment]
> after that , running train.py, it throws as following:
> 
> ```
> /opt/homebrew/Caskroom/miniconda/base/envs/torch-nightly/lib/python3.8/site-packages/torch/amp/autocast_mode.py:204: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
>   warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
> Traceback (most recent call last):
>   File "train.py", line 104, in <module>
>     ctx = nullcontext() if device_type == 'cpu' else torch.amp.autocast(device_type=device_type, dtype=ptdtype)
>   File "/opt/homebrew/Caskroom/miniconda/base/envs/torch-nightly/lib/python3.8/site-packages/torch/amp/autocast_mode.py", line 233, in __init__
>     if self.fast_dtype == torch.bfloat16 and not torch.cuda.is_bf16_supported():
>   File "/opt/homebrew/Caskroom/miniconda/base/envs/torch-nightly/lib/python3.8/site-packages/torch/cuda/__init__.py", line 113, in is_bf16_supported
>     return torch.cuda.get_device_properties(torch.cuda.current_device()).major >= 8 and cuda_maj_decide
>   File "/opt/homebrew/Caskroom/miniconda/base/envs/torch-nightly/lib/python3.8/site-packages/torch/cuda/__init__.py", line 561, in current_device
>     _lazy_init()
>   File "/opt/homebrew/Caskroom/miniconda/base/envs/torch-nightly/lib/python3.8/site-packages/torch/cuda/__init__.py", line 230, in _lazy_init
>     raise AssertionError("Torch not compiled with CUDA enabled")
> AssertionError: Torch not compiled with CUDA enabled
> ```
> 
> Any idea?
> 
> thanks.

(If using macOS) Edit the file `train.py` at line 72: `device = 'cpu'`, and `compile = False` at line 74. Reason: Andrej mentioned ' on macbook, do not torch compile the model'.

**Comment by stefanbschneider** [comment]
For me, training works fine on M1 using `--device=mps` and `--compile=False`.

Full command for training on shakespeare copied from the readme with `mps`:

```
python train.py config/train_shakespeare_char.py --device=mps --compile=False --eval_iters=20 --log_interval=1 --block_size=64 --batch_size=12 --n_layer=4 --n_head=4 --n_embd=128 --max_iters=2000 --lr_decay_iters=2000 --dropout=0.0
```

But I have iteration times of 700-800ms; 2000 iters took much longer than 3min. In the end, I have a loss of 1.2.

**Comment by stefanbschneider** [comment]
I run into a different problem with sampling though:

```
% python sample.py --out_dir=out-shakespeare-char --device=mps
Overriding: out_dir = out-shakespeare-char
Overriding: device = mps
number of parameters: 0.80M
Loading meta from data/shakespeare_char/meta.pkl...
/AppleInternal/Library/BuildRoots/c651a45f-806e-11ed-a221-7ef33c48bc85/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Types/MPSNDArray.mm:88: failed assertion `[MPSNDArrayDescriptor sliceDimension:withSubrange:] error: the range subRange.start + subRange.length does not fit in dimension[2] (1)'
zsh: abort      python sample.py --out_dir=out-shakespeare-char --device=mps
```

**Comment by stefanbschneider** [comment]
The sample error seems to come from using `--device=mps` for sampling. Using `--device=cpu` works fine. Not sure why since training with `mps` works fine.

**Comment by Maxhirez** [comment]
Now that torch has support for metal, have you considered a version that tests for mps gpus and can leverage them?  I've played with it a little and not had great luck (for example, trying to run the CLIP model and local gpt-j examples.)  I plan to experiment with converting the "sample.py" example later today, but it would be nice to see it done correctly by someone experienced!

**Comment by rekram1-node** [comment]
> > after that , running train.py, it throws as following:
> > ```
> > /opt/homebrew/Caskroom/miniconda/base/envs/torch-nightly/lib/python3.8/site-packages/torch/amp/autocast_mode.py:204: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
> >   warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
> > Traceback (most recent call last):
> >   File "train.py", line 104, in <module>
> >     ctx = nullcontext() if device_type == 'cpu' else torch.amp.autocast(device_type=device_type, dtype=ptdtype)
> >   File "/opt/homebrew/Caskroom/miniconda/base/envs/torch-nightly/lib/python3.8/site-packages/torch/amp/autocast_mode.py", line 233, in __init__
> >     if self.fast_dtype == torch.bfloat16 and not torch.cuda.is_bf16_supported():
> >   File "/opt/homebrew/Caskroom/miniconda/base/envs/torch-nightly/lib/python3.8/site-packages/torch/cuda/__init__.py", line 113, in is_bf16_supported
> >     return torch.cuda.get_device_properties(torch.cuda.current_device()).major >= 8 and cuda_maj_decide
> >   File "/opt/homebrew/Caskroom/miniconda/base/envs/torch-nightly/lib/python3.8/site-packages/torch/cuda/__init__.py", line 561, in current_device
> >     _lazy_init()
> >   File "/opt/homebrew/Caskroom/miniconda/base/envs/torch-nightly/lib/python3.8/site-packages/torch/cuda/__init__.py", line 230, in _lazy_init
> >     raise AssertionError("Torch not compiled with CUDA enabled")
> > AssertionError: Torch not compiled with CUDA enabled
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Any idea?
> > thanks.
> 
> (If using macOS) Edit the file `train.py` at line 72: `device = 'cpu'`, and `compile = False` at line 74. Reason: Andrej mentioned ' on macbook, do not torch compile the model'.

This worked perfect thanks!

**Comment by robertu7** [comment]
here is a fix if you faced a error from `torch.cuda.is_bf16_supported()`:

```diff
- dtype = 'bfloat16' if torch.cuda.is_bf16_supported() else 'float16' # 'float32', 'bfloat16', or 'float16', the latter will auto implement a GradScaler
+ dtype = 'float16' # 'float32', 'bfloat16', or 'float16', the latter will auto implement a GradScaler
```

**Comment by dhingratul** [comment]
@robertu7 Are you still running it with compile=False ?

**Comment by mepc36** [comment]
> For me, training works fine on M1 using `--device=mps` and `--compile=False`.
> 
> Full command for training on shakespeare copied from the readme with `mps`:
> 
> ```
> python train.py config/train_shakespeare_char.py --device=mps --compile=False --eval_iters=20 --log_interval=1 --block_size=64 --batch_size=12 --n_layer=4 --n_head=4 --n_embd=128 --max_iters=2000 --lr_decay_iters=2000 --dropout=0.0
> ```
> 
> But I have iteration times of 700-800ms; 2000 iters took much longer than 3min. In the end, I have a loss of 1.2.

Thank you @stefanbschneider, your one liner CLI command worked as a drop-in replacement for the `train.py` command given in the README.

**Comment by stevef1uk** [comment]
I managed to get this  towork on my M2 pro Mac with compilation by doing a couple of things:

1. Wrote a wrapper for g++-12, which I set in the CXX env variable. As my bash scripting is rusty I used OpenAI to create the basic script. All it does is change my script name to /opt/homebrew/bin/g++-12 (which is where brew installed the compeller that supports OpenMP as the default Apple one doesn't) and remove the -Xclang parameter as that isn't understood by g++-12
2. Edited the train.py code to set device = 'mps' (check you have this capability via: python -c "import torch;print(torch.__version__, torch.backends.mps.is_available())"
3. Added these 2 lines to train.py
```
import torch._dynamo
torch._dynamo.config.suppress_errors = True
```

Then I was able to run the training and the model was compiled and run on my mac's GPU. The difference was significant, with compiled plus cpu set each training iteration took 30s whereas with the GPU used it took 0.5s. I also changed the number of interaction to 6000 rather than 600000 as my patience is limited.

**Comment by bdytx5** [comment]
@stevef1uk bro u are goated haha
