### ISSUE TITLE
Key Error after fine tuning with gpt2

### ISSUE THREAD

**Issue by thatfilmguy** [karpathy/nanoGPT#169]
I'm getting the following error after running sample.py to generate text:

Traceback (most recent call last):
  File "/Users/codypyper/nanoGPT-master/sample.py", line 88, in <module>
    print(decode(y[0].tolist()))
  File "/Users/codypyper/nanoGPT-master/sample.py", line 68, in <lambda>
    decode = lambda l: ''.join([itos[i] for i in l])
  File "/Users/codypyper/nanoGPT-master/sample.py", line 68, in <listcomp>
    decode = lambda l: ''.join([itos[i] for i in l])
KeyError: 271

I trained the model originally on a custom dataset that I prepared. That worked fine, created a usable checkpoint and generated text using sample.py perfectly. 

I then fine tuned my model by running:

python train.py config/finetune_project.py

That step works fine, and the checkpoint was updated. But then when I run a sample.py with the updated checkpoint, i get the error mentioned earlier, "KeyError: 271"

Running on a 
MacBook Pro (16-inch, 2021)
OS 12.5.1
Apple M1 Max
64GB Ram

Thanks for the help

**Comment by nirvitarka** [comment]
I got the same error when the prompt I gave had a question mark ("?"). It worked fine after I remove that "?"

**Comment by thatfilmguy** [comment]
I got it working. I ran the wrong prepare.py originally. I copied the prepare.py by copying the data/shakespeare-chars folder instead of the data/shakespeare. Thanks nirvitarka for the comment btw, good to know about the '?'

**Comment by GalMoore** [comment]
Thanks @thatfilmguy - had the same issue and same resolution :)
