### ISSUE TITLE
 local variable 'beta1' referenced before assignment

### ISSUE THREAD

**Issue by kevindany** [karpathy/nanoGPT#186]
When I run: python train.py config/train_shakespeare_char.py, it run into error as below, please help.

Below is what I print the optimizer: 
 AdamW (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.99)
    eps: 1e-08
    lr: 0.001
    weight_decay: 0.1

Parameter Group 1
    amsgrad: False
    betas: (0.9, 0.99)
    eps: 1e-08
    lr: 0.001
    weight_decay: 0.0
)

----------------------- error message --------------------------
step 0: train loss 4.2874, val loss 4.2823
Traceback (most recent call last):
  File "train.py", line 312, in <module>
    scaler.step(optimizer)
  File "/home/xx/miniconda3/envs/py38/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 311, in step
    return optimizer.step(*args, **kwargs)
  File "/home/xx/miniconda3/envs/py38/lib/python3.8/site-packages/torch/optim/optimizer.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "/home/xx/miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/xx/miniconda3/envs/py38/lib/python3.8/site-packages/torch/optim/adamw.py", line 117, in step
    beta1,
UnboundLocalError: local variable 'beta1' referenced before assignment

**Comment by Nikolaj-K** [comment]
Note: Your error comes from with packages. Googling shows this has been reported in other repos a few times, and I figure it might be a version thing. This may or may not explain why it pops up for you and not others.

**Comment by kevindany** [comment]
> 

right, I had figured it out, very appericate it!
