### ISSUE TITLE
GPT-2 encode/decode error when using M2 MPS

### ISSUE THREAD

**Issue by elcolie** [karpathy/nanoGPT#255]
I can train shakespeare with MPS. But when I run it `tiktoken` raises an error as follow.
```bash
❯  python sample.py --out_dir=out-shakespeare --device=mps
Overriding: out_dir = out-shakespeare
Overriding: device = mps
number of parameters: 1555.97M
No meta.pkl found, assuming GPT-2 encodings...
Traceback (most recent call last):
  File "sample.py", line 88, in <module>
    print(decode(y[0].tolist()))
  File "sample.py", line 74, in <lambda>
    decode = lambda l: enc.decode(l)
  File "/Users/sarit/.pyenv/versions/nanoGPT/lib/python3.8/site-packages/tiktoken/core.py", line 254, in decode
    return self._core_bpe.decode_bytes(tokens).decode("utf-8", errors=errors)
OverflowError: can't convert negative int to unsigned
```

The problem is `model.generate()` always produce negative value tensor then `tiktoken` crash.

**Comment by elcolie** [comment]
It is [known issue](https://github.com/pytorch/pytorch/issues/92752).
