### ISSUE TITLE
--device=cpu not working?

### ISSUE THREAD

**Issue by leejw51** [karpathy/nanoGPT#293]
seems --device=cpu not working,
i tested on apple m1

--device=cpu, --device=mps 
speed is the same?

**Comment by sss-ng** [comment]
Same here
```
$ python train.py config/train_shakespeare_char.py --device=cpu --compile=False --eval_iters=20 --log_interval=1 --block_size=64 --batch_size=12 --n_layer=4 --n_head=4 --n_embd=128 --max_iters=2000 --lr_decay_iters=2000 --dropout=0.0
Traceback (most recent call last):
  File "/tmp/nanoGPT/train.py", line 73, in <module>
    dtype = 'bfloat16' if torch.cuda.is_bf16_supported() else 'float16' # 'float32', 'bfloat16', or 'float16', the latter will auto implement a GradScaler
  File "/home/sam/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 122, in is_bf16_supported
    return torch.cuda.get_device_properties(torch.cuda.current_device()).major >= 8 and cuda_maj_decide
  File "/home/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 674, in current_device
    _lazy_init()
  File "/home/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```

**Comment by 0dB** [comment]
This seems to be connected with #304, #306, #307.

I have this error too and had to revert the commit https://github.com/karpathy/nanoGPT/commit/eb33b8bf1c979c4b414a3f126db8dc974d8f456c to get the code working again. I use device=mps, not cuda, so I suppose that is why torch.cuda.is_bf16_supported() does not work for me.
