### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by dhingratul** [karpathy/nanoGPT#304]
Details: Training with CPU doesn't work

Reproducer:
``` python train.py config/train_shakespeare_char.py --device=cpu --compile=False --eval_iters=20 --log_interval=1 --block_size=64 --batch_size=12 --n_layer=4 --n_head=4 --n_embd=128 --max_iters=2000 --lr_decay_iters=2000 --dropout=0.0 ```

Logs
```
Traceback (most recent call last):
  File "/srambled_path/nanoGPT/train.py", line 73, in <module>
    dtype = 'bfloat16' if torch.cuda.is_bf16_supported() else 'float16' # 'float32', 'bfloat16', or 'float16', the latter will auto implement a GradScaler
  File "/usr/local/anaconda3/lib/python3.9/site-packages/torch/cuda/__init__.py", line 102, in is_bf16_supported
    return torch.cuda.get_device_properties(torch.cuda.current_device()).major >= 8 and cuda_maj_decide
  File "/usr/local/anaconda3/lib/python3.9/site-packages/torch/cuda/__init__.py", line 552, in current_device
    _lazy_init()
  File "/usr/local/anaconda3/lib/python3.9/site-packages/torch/cuda/__init__.py", line 221, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

**Comment by karpathy** [comment]
Bleh I'm guessing it's because `torch.cuda` throws an error in this case, so we have to gate it

**Comment by dhingratul** [comment]
@karpathy Same behavior in sample.py, i gated it in #304

**Comment by 0dB** [comment]
I have this error too and had to revert the commit eb33b8b to get the code working again. I use `device=mps`, not `cuda`, so I suppose that is why `torch.cuda.is_bf16_supported()` does not work for me.

**Comment by 0dB** [comment]
I don't know if this was the right solution... before eb33b8b on my MacBook with `mps` `dtype` was `bfloat16` now with this latest merge with 1eaceae it looks like I will be getting `float16` which I don't want?

**Comment by dhingratul** [comment]
@0dB This actually doesn't work for me in training:
```
torch._dynamo.exc.BackendCompilerFailed: debug_wrapper raised AssertionError: Torch not compiled with CUDA enabled
```
