### ISSUE TITLE
AssertionError when trying to run sample.py

### ISSUE THREAD

**Issue by RexNecross** [karpathy/nanoGPT#439]
When i try to run sample.py with shakespeare sample data i get:

Traceback (most recent call last):
  File "C:\Users\joachim.bischof\nanoGPT\nanoGPT\sample.py", line 23, in <module>
    exec(open('configurator.py').read()) # overrides from command line or config file
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 31, in <module>
AssertionError

**Comment by VatsaDev** [comment]
Whats your environment? Do you have the config file? Did you add anything to the CLI? Is every command formatted right?

**Comment by WeileiZeng** [comment]
your cmd is not in a valid format. check `configurator.py` for the format, it could be either config.file or --config-arg
