### ISSUE TITLE
no cuda training does not work.

### ISSUE THREAD

**Issue by BurkenDev** [karpathy/nanoGPT#460]
This needs fixing since that package in debian 12 isn't compiled with cuda, you should have this be able to train without cuda as well.
Up to us to choose whether we want cpu or gpu training.

Traceback (most recent call last):
  File "/root/nanoGPT/train.py", line 193, in <module>
    model.to(device)
  File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 989, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 664, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/torch/cuda/__init__.py", line 221, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by ikeman32** [comment]
Disable compile by setting compile=False
I ran into this very problem and solved it that way.
