### ISSUE TITLE
Training fails on Python 3.12 on either GPU or CPU

### ISSUE THREAD

**Issue by tigran123** [karpathy/nanoGPT#477]
I have just tried (following the README) to train the "tiny shakespeare" (character-level) on NVIDIA GTX 1060 and it fails:

```
$ python3.12 train.py config/train_shakespeare_char.py 
Overriding config with config/train_shakespeare_char.py:
# train a miniature character-level shakespeare model
# good for debugging and playing on macbooks and such

out_dir = 'out-shakespeare-char'
eval_interval = 250 # keep frequent because we'll overfit
eval_iters = 200
log_interval = 10 # don't print too too often

# we expect to overfit on this small dataset, so only save when val improves
always_save_checkpoint = False

wandb_log = False # override via command line if you like
wandb_project = 'shakespeare-char'
wandb_run_name = 'mini-gpt'

dataset = 'shakespeare_char'
gradient_accumulation_steps = 1
batch_size = 64
block_size = 256 # context of up to 256 previous characters

# baby GPT model :)
n_layer = 6
n_head = 6
n_embd = 384
dropout = 0.2

learning_rate = 1e-3 # with baby networks can afford to go a bit higher
max_iters = 5000
lr_decay_iters = 5000 # make equal to max_iters usually
min_lr = 1e-4 # learning_rate / 10 usually
beta2 = 0.99 # make a bit bigger because number of tokens per iter is small

warmup_iters = 100 # not super necessary potentially

# on macbook also add
# device = 'cpu'  # run on cpu only
# compile = False # do not torch compile the model

tokens per iteration will be: 16,384
found vocab_size = 65 (inside data/shakespeare_char/meta.pkl)
Initializing a new model from scratch
number of parameters: 10.65M
num decayed parameter tensors: 26, with 10,740,096 parameters
num non-decayed parameter tensors: 13, with 4,992 parameters
using fused AdamW: True
compiling the model... (takes a ~minute)
Traceback (most recent call last):
  File "/home/tigran/python/ml/nanoGPT/train.py", line 208, in <module>
    model = torch.compile(model) # requires PyTorch 2.0
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/tigran/.local/lib/python3.12/site-packages/torch/__init__.py", line 1801, in compile
    raise RuntimeError("Dynamo is not supported on Python 3.12+")
RuntimeError: Dynamo is not supported on Python 3.12+
$ pip3.12 list |grep torch
torch                     2.2.2
torchaudio                2.2.2
torchvision               0.17.2
$ nvidia-smi 
Fri Apr 26 18:02:59 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.171.04             Driver Version: 535.171.04   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1060 6GB    Off | 00000000:01:00.0  On |                  N/A |
| 29%   43C    P0              25W / 120W |    799MiB /  6144MiB |      5%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1625      G   /usr/lib/xorg/Xorg                          365MiB |
|    0   N/A  N/A      1759      G   /usr/bin/gnome-shell                        128MiB |
|    0   N/A  N/A      2224      G   ...seed-version=20240426-050101.464000      237MiB |
+---------------------------------------------------------------------------------------+

```

The data preparation step works fine, of course.

Now, if I train using cpu it fails the assertion:

```
$ python3.12 train.py config/train_shakespeare_char.py --device=cpu --compile=False --eval_iters=20 --log_interval=1 --block_size=64 --batch_size=12 --n_layer=4 --n_head=4 --n_embd=128 --max_iters=2000 --lr_decay_iters=2000 --dropout=0.0
Overriding config with config/train_shakespeare_char.py:
# train a miniature character-level shakespeare model
# good for debugging and playing on macbooks and such

out_dir = 'out-shakespeare-char'
eval_interval = 250 # keep frequent because we'll overfit
eval_iters = 200
log_interval = 10 # don't print too too often

# we expect to overfit on this small dataset, so only save when val improves
always_save_checkpoint = False

wandb_log = False # override via command line if you like
wandb_project = 'shakespeare-char'
wandb_run_name = 'mini-gpt'

dataset = 'shakespeare_char'
gradient_accumulation_steps = 1
batch_size = 64
block_size = 256 # context of up to 256 previous characters

# baby GPT model :)
n_layer = 6
n_head = 6
n_embd = 384
dropout = 0.2

learning_rate = 1e-3 # with baby networks can afford to go a bit higher
max_iters = 5000
lr_decay_iters = 5000 # make equal to max_iters usually
min_lr = 1e-4 # learning_rate / 10 usually
beta2 = 0.99 # make a bit bigger because number of tokens per iter is small

warmup_iters = 100 # not super necessary potentially

# on macbook also add
# device = 'cpu'  # run on cpu only
# compile = False # do not torch compile the model

Overriding: device = cpu
Overriding: compile = False
Overriding: eval_iters = 20
Overriding: log_interval = 1
Overriding: block_size = 64
Overriding: batch_size = 12
Overriding: n_layer = 4
Overriding: n_head = 4
Overriding: n_embd = 128
Overriding: max_iters = 2000
Overriding: lr_decay_iters = 2000
Overriding: dropout = 0.0
tokens per iteration will be: 768
found vocab_size = 65 (inside data/shakespeare_char/meta.pkl)
Initializing a new model from scratch
number of parameters: 0.80M
num decayed parameter tensors: 18, with 802,944 parameters
num non-decayed parameter tensors: 9, with 1,152 parameters
using fused AdamW: False
step 0: train loss 4.1676, val loss 4.1649
Traceback (most recent call last):
  File "/home/tigran/python/ml/nanoGPT/train.py", line 305, in <module>
    scaler.scale(loss).backward()
    ^^^^^^^^^^^^^^^^^^
  File "/home/tigran/.local/lib/python3.12/site-packages/torch/cuda/amp/grad_scaler.py", line 203, in scale
    assert outputs.is_cuda or outputs.device.type == "xla"
AssertionError
```

On my old ThinkPad T450s laptop the training using cpu works fine. The versions of all python packages are the same, but obviously no CUDA on a T450s.

**Comment by tigran123** [comment]
On the first issue I see it is a PyTorch bug https://github.com/pytorch/pytorch/issues/120233 but the second issue is still a bit of a mystery. I can see it is discussed at https://github.com/pytorch/xla/issues/3559 but I am not 100% sure that it is the same problem...

**Comment by tigran123** [comment]
Re-tested on another machine which has NVIDIA RTX 2080 Ti and the result is exactly the same, so I updated the title of this issue accordingly. The key here is Python 3.12 (specifically I use 3.12.3 on all machines).

**Comment by tigran123** [comment]
With the option `--compile=False` it works on RTX 2080 Ti, so the problem has a workaround and the issue can be closed now.
