### ISSUE TITLE
torchrun on L40S Error:torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

### ISSUE THREAD

**Issue by Precola** [karpathy/nanoGPT#545]
I have two L40S.
when I run `torchrun --standalone --nproc_per_node=2 train.py config/train_gpt2.py`,
the errors are :
`
using fused AdamW: True
compiling the model... (takes a ~minute)
using fused AdamW: True
compiling the model... (takes a ~minute)
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/zoe/nanoGPT/train.py", line 253, in <module>
[rank0]:     wandb.init(project=wandb_project, name=wandb_run_name, config=config, mode="offline") # id="1j6c02w
m", resume="must"
[rank0]: AttributeError: module 'wandb' has no attribute 'init'
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/zoe/nanoGPT/train.py", line 306, in <module>
[rank1]:     logits, loss = model(X, Y)
...
[rank1]: While executing %submod_0 : [num_users=2] = call_module[target=submod_0](args = (%l_idx_, %l__s[0/1908]ansformer_h_0_ln_1_weight), kwargs = {})
[rank1]: Original traceback:
[rank1]: None

[rank1]: Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information

[rank1]: You can suppress this exception and fall back to eager by setting:
[rank1]:     import torch._dynamo
[rank1]:     torch._dynamo.config.suppress_errors = True

W0815 16:57:35.569000 139842847601088 torch/distributed/elastic/multiprocessing/api.py:849] Sending process 265741 closing signal SIGTERM
E0815 16:57:35.632000 139842847601088 torch/distributed/elastic/multiprocessing/api.py:824] failed (exitcode: 1) local_rank: 0 (pid: 265740) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.3.1', 'console_scripts', 'torchrun')())
  File "/usr/lib/python3/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/torch/distributed/run.py", line 879, in main
    run(args)
  File "/usr/lib/python3/dist-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/usr/lib/python3/dist-packages/torch/distributed/launcher/api.py", line 130, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/lib/python3/dist-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
\============================================================
train.py FAILED
\------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
\------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-15_16:57:35
  host      : rap-p99
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 265740)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
\============================================================
`

It seems that "wandb" and "triton" have problems, but when I run `python train.py config/train_gpt2.pt`, there is no problems.

>

**Comment by Precola** [comment]
Oh I fixed it.

Because I used "virtualenv --system ~/venv" to construct a virtual env and torch is in the system but "wandb" and "triton" in the virtual env. So there is errors.

So I used `python -m torch.distributed.run --standalone --nproc_per_node=2 train.py config/train_gpt2.py` to replace `torchrun --standalone --nproc_per_node=2 train.py config/train_gpt2.py`
