### ISSUE TITLE
Error when using Pytorch 2.0 (Compile=False)

### ISSUE THREAD

**Issue by HanL2021** [karpathy/nanoGPT#62]
Run train.py using "torchrun --standalone --nproc_per_node=1 train.py --dataset=shakespeare --dtype=float32 --batch_size=8 --compile=True" and got the following error:

master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
Traceback (most recent call last):
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1087, in run_node
c    return node.target(*args, **kwargs)
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 916, in __torch_dispatch__
    r = func(*args, **kwargs)
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/_ops.py", line 284, in __call__
    return self._op(*args, **kwargs or {})
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/_prims_common/wrappers.py", line 209, in _fn
    result = fn(*args, **kwargs)
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/_prims_common/wrappers.py", line 119, in _fn
    result = fn(**bound.arguments)
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/_refs/__init__.py", line 974, in add
    return prims.add(a, b)
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/_ops.py", line 284, in __call__
    return self._op(*args, **kwargs or {})
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/_prims/__init__.py", line 349, in _elementwise_meta
    shape = utils.extract_shape(*args_, allow_cpu_scalar_tensors=True)
AttributeError: module 'torch._prims.utils' has no attribute 'extract_shape'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1046, in get_fake_value
    return wrap_fake_exception(
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 721, in wrap_fake_exception
    return fn()
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1047, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1099, in run_node
    raise RuntimeError(
RuntimeError: Failed running call_function <built-in function add>(*(FakeTensor(FakeTensor(..., device='meta', size=(8, 1024, 768)), cuda:0), FakeTensor(FakeTensor(..., device='meta', size=(1, 1024, 768)), cuda:0)), **{}):
module 'torch._prims.utils' has no attribute 'extract_shape'
(scroll up for backtrace)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/p/work/liux3790/nanoGPT/train.py", line 241, in <module>
    losses = estimate_loss()
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/p/work/liux3790/nanoGPT/train.py", line 202, in estimate_loss
    logits, loss = model(X, Y)
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1488, in _call_impl
    return forward_call(*args, **kwargs)
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1153, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1106, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1488, in _call_impl
    return forward_call(*args, **kwargs)
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 83, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 212, in _fn
    return fn(*args, **kwargs)
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 330, in catch_errors
    return hijacked_callback(frame, cache_size, hooks)
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 480, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 103, in _fn
    return fn(*args, **kwargs)
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 94, in time_wrapper
    r = func(*args, **kwargs)
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 339, in _convert_frame_assert
    return _compile(
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 400, in _compile
    out_code = transform_code_object(code, transform)
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 341, in transform_code_object
    transformations(instructions, code_options)
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 387, in transform
    tracer.run()
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1692, in run
    super().run()
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 538, in run
    and self.step()
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 501, in step
    getattr(self, inst.opname)(inst)
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 137, in impl
    self.push(fn_var.call_function(self, self.popn(nargs), {}))
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/_dynamo/variables/builtin.py", line 288, in call_function
    return wrap_fx_proxy(tx, proxy, **options)
 File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/_dynamo/variables/builder.py", line 752, in wrap_fx_proxy
    return wrap_fx_proxy_cls(
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/_dynamo/variables/builder.py", line 787, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx)
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1066, in get_fake_value
    raise TorchRuntimeError() from e
torch._dynamo.exc.TorchRuntimeError:

from user code:
   File "/p/work/liux3790/nanoGPT/model.py", line 137, in forward
    x = self.transformer.drop(tok_emb + pos_emb)

Set torch._dynamo.config.verbose=True for more information

You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 266712) of binary: /p/home/liux3790/miniconda3/bin/python
Traceback (most recent call last):
  File "/p/home/liux3790/miniconda3/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/distributed/run.py", line 779, in main
    run(args)
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/distributed/run.py", line 770, in run
    elastic_launch(
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/p/home/liux3790/miniconda3/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-01-17_21:51:28
  host      : nid06029.cm.cluster
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 266712)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by MustafaAlahmid** [comment]
just install gcc compiler 

`sudo apt-get install build-essential
`

or 

`sudo apt install gcc-11`
