### ISSUE TITLE
my Cuda device only supports float16

### ISSUE THREAD

**Issue by breadbrowser** [karpathy/nanoGPT#84]
PS F:\downloads\nanoGPT-master\nanoGPT-master> python train.py --learning_rate=0.005 --wandb_log=True                   Overriding: learning_rate = 0.005
Overriding: wandb_log = True
Traceback (most recent call last):
  File "train.py", line 101, in <module>
    ctx = nullcontext() if device_type == 'cpu' else torch.amp.autocast(device_type=device_type, dtype=ptdtype)
  File "F:\python3.8.10\lib\site-packages\torch\amp\autocast_mode.py", line 225, in __init__
    raise RuntimeError('Current CUDA Device does not support bfloat16. Please switch dtype to float16.')
RuntimeError: Current CUDA Device does not support bfloat16. Please switch dtype to float16.

**Comment by PhillzMike** [comment]
You can change the default dtype to `float16` using the dtype flag.

Andrej mentioned you might have to add a gradient scaler since the range for float16 is small, see this issue. https://github.com/karpathy/nanoGPT/issues/8

Also, you can decide to with float32 but training will be much slower

**Comment by karpathy** [comment]
Now `float16` is supported, see recent commit/PR.

**Comment by MaximeGr00** [comment]
> You can change the default dtype to `float16` using the dtype flag.
> 
> Andrej mentioned you might have to add a gradient scaler since the range for float16 is small, see this issue. #8
> 
> Also, you can decide to with float32 but training will be much slower

Hello, I feel like this might be obvious but i couldn't find anything while researching. Could you detail the steps to change the default dtype to float16 ?

**Comment by philippludwig** [comment]
But how to activate `float16`? I am running into this while trying to follow the quick start and have to clue what to do now.

**Comment by webinn** [comment]
> But how to activate `float16`? I am running into this while trying to follow the quick start and have to clue what to do now.

See train.py
`dtype = 'float16'`

**Comment by breadbrowser** [comment]
> You can change the default dtype to `float16` using the dtype flag.
> 
> Andrej mentioned you might have to add a gradient scaler since the range for float16 is small, see this issue. #8
> 
> Also, you can decide to with float32 but training will be much slower

i just started using huggingface trainer and it was 30 times easier
